---
- name: "Retrieve information about virtual machine {{ openshift_vm_name }}"
  kubernetes.core.k8s_info:
    api_key: "{{ api_key }}"
    kind: VirtualMachine
    namespace: "{{ openshift_vm_namespace }}"
    name: "{{ openshift_vm_name }}"
  register: vm_info

- name: "set vm_exist fact"
  ansible.builtin.set_fact:
    vm_exist: "{{ true if vm_info.resources[0].metadata.name is defined else false }}"

- include_tasks: create.yml
  when: openshift_vm_action == "create" and vm_exist is false

- name: "Exit with a message" 
  ansible.builtin.debug:
    msg: "A Virtual machine with the name {{ openshift_vm_name }} already exist in project {{ openshift_vm_namespace }}"
  when: openshift_vm_action == "create" and vm_exist is true

- include_tasks: delete.yml
  when: openshift_vm_action == "delete" and vm_exist is true

- name: "Exit with a message" 
  ansible.builtin.debug:
    msg: "A Virtual machine with the name {{ openshift_vm_name }} does not exist in project {{ openshift_vm_namespace }}"
  when: openshift_vm_action == "delete" and vm_exist is false