---
# tasks file for openshift-vm
- name: "Create virtual machine {{ openshift_vm_name }} with multus network interface"
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    state: present
    template: "vm_definition.yaml.j2"
    wait: yes

- name: "Start virtual machine {{ openshift_vm_name }}"
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    kind: VirtualMachine
    name: "{{ openshift_vm_name }}"
    definition:
      metadata:
        namespace: "{{ openshift_vm_namespace }}"
      spec:
        running: true
    wait: yes
    wait_condition:
      status: "True"
      type: "Ready"

- name: " get information about virtual machine {{ openshift_vm_name }}"
  kubernetes.core.k8s_info:
    api_key: "{{ api_key }}"
    kind: VirtualMachine
    name: "{{ openshift_vm_name }}"
    namespace: "{{ openshift_vm_namespace }}"
  register: vm_info

- name: Print vm_info
  ansible.builtin.debug:
    var: vm_info
    verbosity: 2