---
# tasks file for openshift-vm
- name: Create virtual machine 'myvm' with multus network interface
  kubernetes.core.k8s:
    api_key: "{{ api_key }}"
    state: present
    template: "vm_definition.yaml.j2"
    wait: yes
    