---
# tasks file for openshift-vm
- name: Create virtual machine 'myvm' with multus network interface
  community.kubevirt.kubevirt_vm:
    api_key: "{{ api_key }}"
    name: myvm
    namespace: ansible-testing
    memory: 512M
    interfaces:
      - name: default
        bridge: {}
        network:
          pod: {}
      - name: mynet
        bridge: {}
        network:
          multus:
            networkName: mynetconf
    datavolumes:
      - name: myvm-test-rootdisk
        source:
          pvc:
            name: rhel8-211018-template
            namespace: openshift-virtualization-os-images
        pvc:
          accessModes:
            - ReadWriteOnce
          storage: 15Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
